name: Docker Image Scan

on:
  push:
    branches:
      - main  

jobs:
  scan:
    runs-on: ubuntu-latest  

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  

    - name: Run Docker Scout vulnerability scan
      uses: docker/scout-action@v1  
      with:
       command: analyze 
       image: debian:bullseye
       summary: true
       format: json
       github-token: ${{ secrets.GITHUB_TOKEN }}
       write-comment: true
